In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

In [ ]:
df = pd.read_csv("ai_student_impact_dataset (1).csv")
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

# Data Preparing

In [ ]:
df = df.rename(columns={
    "Major_Category": "major",
    "Year_of_Study": "study_year",
    "Pre_Semester_GPA": "pre_gpa",
    "Weekly_GenAI_Hours": "genai_hours",
    "Primary_Use_Case": "use_case",
    "Prompt_Engineering_Skill": "prompt_skill",
    "Tool_Diversity": "tool_diversity",
    "Paid_Subscription": "paid_sub",
    "Traditional_Study_Hours": "study_hours",
    "Perceived_AI_Dependency": "ai_dependency",
    "Institutional_Policy": "policy",
    "Anxiety_Level_During_Exams": "exam_anxiety",
    "Post_Semester_GPA": "post_gpa",
    "Skill_Retention_Score": "retention_score",
    "Burnout_Risk_Level": "burnout"
})

In [ ]:
df["gpa_change"] = df["post_gpa"] - df["pre_gpa"]

In [ ]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

In [ ]:
df.drop("Student_ID", axis=1, inplace=True)

In [ ]:
df["paid_sub"] = df["paid_sub"].astype(int)

In [ ]:
categorical_cols = df.select_dtypes(include=['object']).columns
numerical_cols = df.select_dtypes(include=["float64", "int64"]).columns

In [ ]:
for cols in categorical_cols:
  print(f"{cols}: {df[cols].unique()}")

major: ['Humanities' 'Medical' 'Business' 'STEM' 'Arts']
study_year: ['Senior' 'Junior' 'Freshman' 'Sophomore' 'Graduate']
use_case: ['Copywriting/Drafting' 'Ideation' 'Summarizing_Reading'
 'Debugging/Troubleshooting' 'Direct_Answer_Generation']
prompt_skill: ['Beginner' 'Advanced' 'Intermediate']
policy: ['Allowed_With_Citation' 'Strict_Ban' 'Actively_Encouraged']
burnout: ['High' 'Low' 'Medium']

In [ ]:
df.shape

(50000, 16)

In [ ]:
df.describe()

,pre_gpa,genai_hours,tool_diversity,paid_sub,study_hours,ai_dependency,exam_anxiety,post_gpa,retention_score,gpa_change
count,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,3.146102,8.427752,2.80026,0.423080,11.209271,3.505360,4.270760,3.349299,75.798125,0.203197
std,0.478854,8.269490,1.18802,0.494053,5.156426,1.820812,2.144066,0.495673,13.281626,0.187192
min,1.183000,0.000000,1.00000,0.000000,1.000000,1.000000,1.000000,1.000000,10.780000,-0.924000
25%,2.834000,2.390000,2.00000,0.000000,7.560000,2.000000,3.000000,3.023750,66.820000,0.087000
50%,3.210000,5.800000,3.00000,0.000000,11.180000,3.000000,4.000000,3.421000,76.000000,0.204000
75%,3.521000,11.720000,4.00000,1.000000,14.710000,5.000000,6.000000,3.749000,85.190000,0.325000
max,3.998000,40.000000,5.00000,1.000000,35.860000,10.000000,10.000000,4.000000,100.000000,1.008000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   major            50000 non-null  object
 1   study_year       50000 non-null  object
 2   pre_gpa          50000 non-null  float64
 3   genai_hours      50000 non-null  float64
 4   use_case         50000 non-null  object
 5   prompt_skill     50000 non-null  object
 6   tool_diversity   50000 non-null  int64
 7   paid_sub         50000 non-null  int64
 8   study_hours      50000 non-null  float64
 9   ai_dependency    50000 non-null  int64
 10  policy           50000 non-null  object
 11  exam_anxiety     50000 non-null  int64
 12  post_gpa         50000 non-null  float64
 13  retention_score  50000 non-null  float64
 14  burnout          50000 non-null  object
 15  gpa_change       50000 non-null  float64
dtypes: float64(6), int64(4), object(6)
memory usage: 6.1+ MB

In [ ]:
# df.to_csv("ai_student_impact_dataset.csv", index=False)